//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IBaseDto
{
	Id: any;
	CreatedOn: any;
	EntityStatus: number;
}
export interface IBookDto extends IBaseDto
{
	Title: string;
	Chapters: IChapterDto[];
}
export interface IChapterDto extends IBaseDto
{
	BookId: any;
	Title: string;
	Pages: IPageDto[];
}
export interface IPageDto extends IBaseDto
{
	ChapterId: any;
	ParagraphCount: number;
	Number: number;
}
