//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { IBaseDto } from './interfaces';

export interface IBaseApiController
{
	Parameterless() : Observable<IBaseDto>;
	Parametrized(id: any) : Observable<IBaseDto>;
}
