//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { eEntityStatus } from './enums';

export interface IBaseDto
{
	id: string;
	createdOn: Date;
	entityStatus: eEntityStatus;
}
export interface IBookDto extends IBaseDto
{
	title: string;
	chapters: IChapterDto[];
}
export interface IChapterDto extends IBaseDto
{
	bookId: string;
	title: string;
	pages: IPageDto[];
}
export interface IPageDto extends IBaseDto
{
	chapterId: string;
	paragraphCount: number;
	number: number;
}
